- name: Create Hosted Resources
  hosts: oo_first_master
  pre_tasks:
  - set_fact:
      openshift_hosted_router_registryurl: "{{ hostvars[groups.oo_first_master.0].openshift.master.registry_url }}"
  roles:
  - role: openshift_hosted
