---
- name: Install NFS storage plugin dependencies
  action: "{{ ansible_pkg_mgr }} name=nfs-utils state=present"
  when: not openshift.common.is_atomic | bool

- name: Set seboolean to allow nfs storage plugin access from containers
  seboolean:
    name: virt_use_nfs
    state: yes
    persistent: yes
  when: ansible_selinux and ansible_selinux.status == "enabled"

- name: Set seboolean to allow nfs storage plugin access from containers(sandbox)
  seboolean:
    name: virt_sandbox_use_nfs
    state: yes
    persistent: yes
  when: ansible_selinux and ansible_selinux.status == "enabled"
