---
- name: Set haproxy frontend port
  openshift_facts:
    role: loadbalancer
    local_facts:
      frontend_port: "{{ openshift_master_api_port | default(None) }}"

- name: Set loadbalancer facts
  openshift_facts:
    role: loadbalancer
    local_facts:
      limit_nofile: "{{ openshift_loadbalancer_limit_nofile | default(None) }}"
      default_maxconn: "{{ openshift_loadbalancer_default_maxconn | default(None) }}"
      global_maxconn: "{{ openshift_loadbalancer_global_maxconn | default(None) }}"
      frontends:
      - name: atomic-openshift-api
        mode: tcp
        options:
        - tcplog
        binds:
        - "*:{{ openshift.loadbalancer.frontend_port }}"
        default_backend: atomic-openshift-api
      backends:
      - name: atomic-openshift-api
        mode: tcp
        option: tcplog
        balance: source
        servers: "{{ hostvars
                     | oo_select_keys(groups['oo_masters'])
                     | oo_haproxy_backend_masters(openshift.loadbalancer.frontend_port) }}"
